parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Attendance\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Attendance\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Attendance\Tests\Behat\:
        resource: '../tests/Behat/*'

    Attendance\Events\Listener\Logging\ApiLogListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    Attendance\Events\Listener\Authentication\AuthenticatedRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }